# Generated by Django 5.0.2 on 2025-10-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Promo code (stored in UPPERCASE)', max_length=50, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0.01 - 100.00)', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('has_date_window', models.BooleanField(default=False, help_text='If True, promo is valid only between active_from and active_to')),
                ('active_from', models.DateTimeField(blank=True, help_text='Start of validity period (timezone-aware)', null=True)),
                ('active_to', models.DateTimeField(blank=True, help_text='End of validity period (timezone-aware)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
