# Generated by Django 5.0.2 on 2025-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='mini_app_url',
            field=models.URLField(blank=True, help_text='Mini App URL for the shop (e.g., https://t.me/zzz/app)', null=True),
        ),
    ]
