# Generated by Django 5.0.2 on 2025-10-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image', upload_to='products/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.DeleteModel(
            name='ImageAsset',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
