# Generated by Django 5.0.2 on 2025-10-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, help_text='0 = primary image'),
        ),
    ]
