# Generated by Django 5.0.2 on 2025-10-18 21:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text='Phone number (no validation)', max_length=20)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username WITH @ (e.g., @johndoe)', max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], db_index=True, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before discount', max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount from promo code', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final total (subtotal - discount_total)', max_digits=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], db_index=True, default='new', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Customer comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promos.promocode')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(help_text='Product name at order time', max_length=255)),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Effective price at order time (with discount if applicable)', max_digits=12)),
                ('qty', models.IntegerField(help_text='Quantity ordered')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Line total (price_snapshot * qty)', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
