# Generated by Django 5.0.2 on 2025-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed')], db_index=True, default='new', max_length=20),
        ),
    ]
